(cl:in-package fixposition_driver_ros1-msg)
(cl:export '(HEADER-VAL
          HEADER
          INIT_STATUS-VAL
          INIT_STATUS
          FUSION_IMU-VAL
          FUSION_IMU
          FUSION_GNSS1-VAL
          FUSION_GNSS1
          FUSION_GNSS2-VAL
          FUSION_GNSS2
          FUSION_CORR-VAL
          FUSION_CORR
          FUSION_CAM1-VAL
          FUSION_CAM1
          FUSION_WS-VAL
          FUSION_WS
          FUSION_MARKERS-VAL
          FUSION_MARKERS
          IMU_STATUS-VAL
          IMU_STATUS
          IMU_NOISE-VAL
          IMU_NOISE
          IMU_CONV-VAL
          IMU_CONV
          GNSS1_STATUS-VAL
          GNSS1_STATUS
          GNSS2_STATUS-VAL
          GNSS2_STATUS
          BASELINE_STATUS-VAL
          BASELINE_STATUS
          CORR_STATUS-VAL
          CORR_STATUS
          CAM1_STATUS-VAL
          CAM1_STATUS
          WS_STATUS-VAL
          WS_STATUS
          WS_CONV-VAL
          WS_CONV
          MARKERS_STATUS-VAL
          MARKERS_STATUS
          MARKERS_CONV-VAL
          MARKERS_CONV
))