(cl:in-package fixposition_driver_ros1-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIME-VAL
          TIME
          DATE-VAL
          DATE
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          QUALITY-VAL
          QUALITY
          NUM_SV-VAL
          NUM_SV
          IDS-VAL
          IDS
          HDOP_REC-VAL
          HDOP_REC
          PDOP-VAL
          PDOP
          HDOP-VAL
          HDOP
          VDOP-VAL
          VDOP
          RMS_RANGE-VAL
          RMS_RANGE
          STD_MAJOR-VAL
          STD_MAJOR
          STD_MINOR-VAL
          STD_MINOR
          ANGLE_MAJOR-VAL
          ANGLE_MAJOR
          STD_LAT-VAL
          STD_LAT
          STD_LON-VAL
          STD_LON
          STD_ALT-VAL
          STD_ALT
          COVARIANCE-VAL
          COVARIANCE
          COV_TYPE-VAL
          COV_TYPE
          HEADING-VAL
          HEADING
          SPEED-VAL
          SPEED
          COURSE-VAL
          COURSE
          DIFF_AGE-VAL
          DIFF_AGE
          DIFF_STA-VAL
          DIFF_STA
          GNSS_SATS-VAL
          GNSS_SATS
))