(cl:in-package fixposition_driver_ros1-msg)
(cl:export '(HEADER-VAL
          HEADER
          GNSS1_FIX-VAL
          GNSS1_FIX
          GNSS1_NSIG_L1-VAL
          GNSS1_NSIG_L1
          GNSS1_NSIG_L2-VAL
          GNSS1_NSIG_L2
          GNSS2_FIX-VAL
          GNSS2_FIX
          GNSS2_NSIG_L1-VAL
          GNSS2_NSIG_L1
          GNSS2_NSIG_L2-VAL
          GNSS2_NSIG_L2
          CORR_LATENCY-VAL
          CORR_LATENCY
          CORR_UPDATE_RATE-VAL
          CORR_UPDATE_RATE
          CORR_DATA_RATE-VAL
          CORR_DATA_RATE
          CORR_MSG_RATE-VAL
          CORR_MSG_RATE
          STA_ID-VAL
          STA_ID
          STA_LLH-VAL
          STA_LLH
          STA_DIST-VAL
          STA_DIST
))