// Generated by gencpp from file fixposition_driver_ros1/Speed.msg
// DO NOT EDIT!


#ifndef FIXPOSITION_DRIVER_ROS1_MESSAGE_SPEED_H
#define FIXPOSITION_DRIVER_ROS1_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <fixposition_driver_ros1/WheelSensor.h>

namespace fixposition_driver_ros1
{
template <class ContainerAllocator>
struct Speed_
{
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
    : sensors()  {
    }
  Speed_(const ContainerAllocator& _alloc)
    : sensors(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::fixposition_driver_ros1::WheelSensor_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::fixposition_driver_ros1::WheelSensor_<ContainerAllocator> >> _sensors_type;
  _sensors_type sensors;





  typedef boost::shared_ptr< ::fixposition_driver_ros1::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fixposition_driver_ros1::Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_

typedef ::fixposition_driver_ros1::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::fixposition_driver_ros1::Speed > SpeedPtr;
typedef boost::shared_ptr< ::fixposition_driver_ros1::Speed const> SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fixposition_driver_ros1::Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fixposition_driver_ros1::Speed_<ContainerAllocator1> & lhs, const ::fixposition_driver_ros1::Speed_<ContainerAllocator2> & rhs)
{
  return lhs.sensors == rhs.sensors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fixposition_driver_ros1::Speed_<ContainerAllocator1> & lhs, const ::fixposition_driver_ros1::Speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fixposition_driver_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fixposition_driver_ros1::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fixposition_driver_ros1::Speed_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fixposition_driver_ros1::Speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c35c230ca1b330732decce9c593d3ae9";
  }

  static const char* value(const ::fixposition_driver_ros1::Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc35c230ca1b33073ULL;
  static const uint64_t static_value2 = 0x2decce9c593d3ae9ULL;
};

template<class ContainerAllocator>
struct DataType< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fixposition_driver_ros1/Speed";
  }

  static const char* value(const ::fixposition_driver_ros1::Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "####################################################################################################\n"
"#\n"
"#    Copyright (c) 2023  ___     ___\n"
"#                       \\\\  \\\\  /  /\n"
"#                        \\\\  \\\\/  /\n"
"#                         /  /\\\\  \\\\\n"
"#                        /__/  \\\\__\\\\  Fixposition AG\n"
"#\n"
"####################################################################################################\n"
"#\n"
"# Wheel speed input to Fixposition ROS Driver\n"
"#\n"
"#\n"
"####################################################################################################\n"
"\n"
"# Velocity values for one or several WheelSensors\n"
"fixposition_driver_ros1/WheelSensor[] sensors\n"
"\n"
"================================================================================\n"
"MSG: fixposition_driver_ros1/WheelSensor\n"
"####################################################################################################\n"
"#\n"
"#    Copyright (c) 2023  ___     ___\n"
"#                       \\\\  \\\\  /  /\n"
"#                        \\\\  \\\\/  /\n"
"#                         /  /\\\\  \\\\\n"
"#                        /__/  \\\\__\\\\  Fixposition AG\n"
"#\n"
"####################################################################################################\n"
"#\n"
"# Individual wheelspeed measurement\n"
"#\n"
"#\n"
"####################################################################################################\n"
"# Standard metadata\n"
"std_msgs/Header header\n"
"\n"
"# Location of the wheelspeed measurement (one of: RC, FR, FL, RR, RL)\n"
"string location\n"
"\n"
"# Velocity values in [mm/s] as integer 32bit\n"
"int32 vx\n"
"int32 vy\n"
"int32 vz\n"
"\n"
"# Velocity validity\n"
"bool vx_valid\n"
"bool vy_valid\n"
"bool vz_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::fixposition_driver_ros1::Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fixposition_driver_ros1::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fixposition_driver_ros1::Speed_<ContainerAllocator>& v)
  {
    s << indent << "sensors[]" << std::endl;
    for (size_t i = 0; i < v.sensors.size(); ++i)
    {
      s << indent << "  sensors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::fixposition_driver_ros1::WheelSensor_<ContainerAllocator> >::stream(s, indent + "    ", v.sensors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIXPOSITION_DRIVER_ROS1_MESSAGE_SPEED_H
